version: '3.8'
services:

#Back-end spring-boot Application
  kpis-backend:
      image: 'kpis-agiles-backend:latest'
      ports:
         - "8081:8081"
      build:
         context: .
      container_name: kpis-agile-server
      restart: on-failure
      depends_on:
         - db
      environment:
            #compose-postgres name db user pass
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=mypass
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
            - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      networks: # Networks to join (Services on the same network can communicate with each other using their name)
        - backend
        - frontend

#Postgres db
  db:
     image: 'postgres:13.1-alpine'
     restart: on-failure
     container_name: db-kpis-agile
     volumes:
      - ./pgkpis-agile:/var/lib/postgresql/data
     environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=mypass
     networks:
       - backend    

 #Fron-end Angular Application
  kpis-ui:
    image: 'kpis-agiles-frontend:latest'
    build:
         context: ../CICD-kpis-agiles-frontend
         #context: ../kpis-agile-client
    container_name: kpis-agile-ui
    ports:
      - 4200:80
    depends_on:
         - kpis-backend
    networks:
      - frontend

volumes:
  pgkpis-agile:  
  
# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: